### ISSUE TITLE
Deployment failure running gunicorn app:app

### ISSUE THREAD

**Issue by AlexBule** [hikmahealth/hikma-health-backend#32]
Hi, i tried to deploy the hikma-health-backend on render and i got the folowing:

Running 'gunicorn app:app'
infoTraceback (most recent call last):
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/util.py", line 414, in import_app
info    app = getattr(mod, name)
info          ^^^^^^^^^^^^^^^^^^
infoAttributeError: module 'app' has no attribute 'app'
info
infoDuring handling of the above exception, another exception occurred:
info
infoTraceback (most recent call last):
info  File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
info    sys.exit(run())
info             ^^^^^
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
info    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
info    super().run()
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
info    Arbiter(self).run()
info    ^^^^^^^^^^^^^
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
info    self.setup(app)
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup
info    self.app.wsgi()
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
info    self.callable = self.load()
info                    ^^^^^^^^^^^
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
info    return self.load_wsgiapp()
info           ^^^^^^^^^^^^^^^^^^^
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
info    return util.import_app(self.app_uri)
info           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
info  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/util.py", line 418, in import_app
info    raise AppImportError("Failed to find attribute %r in %r." % (name, module))
infogunicorn.errors.AppImportError: Failed to find attribute 'app' in 'app'.

![Screenshot from 2024-07-28 18-40-32](https://github.com/user-attachments/assets/ed483f0e-8762-4968-9529-1c35b7fe2d07)
![Screenshot from 2024-07-28 18-40-10](https://github.com/user-attachments/assets/7cacf67d-fe0b-4fc0-9e26-abfeda1f3e2e)

**Comment by 3210jr** [comment]
If this issue comes back up, please re-open the issue!
